name: Build and Push Examples

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
      - name: Set Mercury Version
        run: |
          MERCURY_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="parent"]/*[local-name()="version"]/text()' pom.xml)
          echo "MERCURY_VERSION=v${MERCURY_VERSION/-SNAPSHOT/}" >> $GITHUB_ENV
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          overwrite-settings: false
      - name: Build native image
        run: mvn package -s .m2/settings.xml -Dcontainer-build -DskipTests -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=150
      - name: Push party-routing-profile-example to quay.io
        id: push-prp-to-quay
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          tags: quay.io/ecosystem-appeng/party-routing-profile-example:${{ env.MERCURY_VERSION }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Push customer-offer-example to quay.io
        id: push-co-to-quay
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          tags: quay.io/ecosystem-appeng/customer-offer-example:${{ env.MERCURY_VERSION }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Push customer-credit-rating-example to quay.io
        id: push-crc-to-quay
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          tags: quay.io/ecosystem-appeng/customer-credit-rating-example:${{ env.MERCURY_VERSION }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}